format_version: 3
pipelines:
  quickstart-ci:
    lock_behavior: lockOnFailure
    group: Quickstart
    materials:
      repo: 
       git: https://github.com/devops-at06/EL.git
       branch: master
    stages: 
      - Build:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "quickstart/"
              artifacts:
                - build:
                    source: quickstart/build/libs/*.jar
                    destination: Build
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - quickstart
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - CodeQuality:
          jobs:
            code-quality:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - quickstart 
  el-web-application:
    lock_behavior: lockOnFailure
    group: WebApplication
    materials:
      repo:
        git: https://github.com/EscarlethFatima/EL.git
        branch: task13
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "webapp/"
              artifacts:
                - build:
                    source: webapp/build/libs/*.war
                    destination: war/
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - webapp/
              artifacts:
                - build:
                    source: webapp/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: webapp/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - Deploy:
          jobs:
            Application:
              tasks:
                - fetch:
                    stage: Build
                    job: building
                    source: war/
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.216
                      - -Pkey_path=/home/go/devops.pem
                      - -Pwar_path=war
                      - -Pwar_name=webapp
                      - -p
                      - webapp/ 
