format-version:3
pipelines:
  lock_behavior: lockOnFailure 
  el-quickstart-ci:
    group: QuickstartProject
    materials:
      repo:
        git: https://github.com/devops-at06/EL.git
        master: gocd
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "quickstart"
              artifacts:
                - build:
                    source: quickstart/build/libs/*.jar
                    destination: war
      - Test:
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - quickstart
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_tests: html/index.html
          
          